//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleClient.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IGetDayOfWeek")]
    public interface IGetDayOfWeek {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetDayOfWeek/GetDayOfWeekUsingService", ReplyAction="http://tempuri.org/IGetDayOfWeek/GetDayOfWeekUsingServiceResponse")]
        string GetDayOfWeekUsingService(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetDayOfWeek/GetDayOfWeekUsingService", ReplyAction="http://tempuri.org/IGetDayOfWeek/GetDayOfWeekUsingServiceResponse")]
        System.Threading.Tasks.Task<string> GetDayOfWeekUsingServiceAsync(System.DateTime date);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGetDayOfWeekChannel : ConsoleClient.ServiceReference.IGetDayOfWeek, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDayOfWeekClient : System.ServiceModel.ClientBase<ConsoleClient.ServiceReference.IGetDayOfWeek>, ConsoleClient.ServiceReference.IGetDayOfWeek {
        
        public GetDayOfWeekClient() {
        }
        
        public GetDayOfWeekClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetDayOfWeekClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetDayOfWeekClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetDayOfWeekClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetDayOfWeekUsingService(System.DateTime date) {
            return base.Channel.GetDayOfWeekUsingService(date);
        }
        
        public System.Threading.Tasks.Task<string> GetDayOfWeekUsingServiceAsync(System.DateTime date) {
            return base.Channel.GetDayOfWeekUsingServiceAsync(date);
        }
    }
}
